### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by joe9** [ivan-m/wl-pprint-text#12]
Hello,

Thanks for sharing wl-pprint-text.

Just want to check if you have plans to release a version with strict text functionality? 

Thanks

**Comment by 3noch** [comment]
Same here.

**Comment by ivan-m** [comment]
Hopefully this weekend.

**Comment by 3noch** [comment]
@ivan-m Anything I can do to help?

**Comment by ivan-m** [comment]
Remind me next week; I'm busy this weekend and I've let this slide long enough that I really should get this out :/

**Comment by 3noch** [comment]
You got it.

**Comment by 3noch** [comment]
@ivan-m  ⏰

**Comment by ivan-m** [comment]
As soon as #15 is resolved.

**Comment by 3noch** [comment]
@ivan-m Because the pending changes require a major version bump, it will take some time before depending packages will upgrade. Any chance you could throw us a bone and push out the major version without waiting for the bugfix?

**Comment by 3noch** [comment]
I'd be happy to help in any way that I can.

**Comment by ivan-m** [comment]
Done, finally.

Sorry for the delay.

**Comment by 3noch** [comment]
@ivan-m Rock on! Thanks so much!
