### ISSUE TITLE
Derive Pretty using Generics?

### ISSUE THREAD

**Issue by joe9** [ivan-m/wl-pprint-text#13]
Hello,

Just want to check if you might be interested in merging the functionality that provides the ability to derive Pretty using Generics.

If you are interested, I can make this (https://github.com/joe9/GenericPretty/blob/master/src/Text/PrettyPrint/GenericPretty.hs  )  as a module to wl-pprint-text?

Thanks

**Comment by ivan-m** [comment]
I would rather not have a typeclass in here I personally find that I need specific custom pretty-printing formatting everywhere; this looks more like a `pretty-show` kind of class on first glance.

**Comment by flip111** [comment]
I'm using this package for just printing (without the "pretty") and i would like this feature. I'm not using `show` as it's suppose to print valid haskell code so i have to have something to print my source code. I was using this library because it supports Text.

**Comment by joe9** [comment]
@flip111 if you want, you can clone my repo and add it to hackage.

**Comment by ivan-m** [comment]
If you want to print your source code, then why don't you want to use `show`?

**Comment by flip111** [comment]
@joe9 i don't want to fork your repo. Perhaps a PR. If you would open issues or leave an email address then we can discuss elsewhere

**Comment by joe9** [comment]
@flip111 please find the package uploaded to hackage https://hackage.haskell.org/package/text-generic-pretty-1.2.1

**Comment by flip111** [comment]
@joe9 thank you :) Maybe one more small request .. it would be nice to have it on stackage too so that it can be installed with stack. Sometimes this is not so hard to do. For example this is how [generic-random was added](https://github.com/fpco/stackage/commit/f6f13871fb08a329515742c05e81de10758a4429) here is the [section in the readme](https://github.com/fpco/stackage#add-your-package) about it.

**Comment by joe9** [comment]
@flip111  https://github.com/fpco/stackage/pull/2160 hope it helps

**Comment by flip111** [comment]
@joe9 i took some time the study the library more carefully. @ivan-m is right that atm it's very similar to show. So actually it has almost similar functionality as [groom](https://hackage.haskell.org/package/groom) (which is implemented in a totally different way). HOWEVER the structures you created are very interesting, i think it could very well serve as a default implementation for pretty printing where it can be override on a per-type base. I was going to use it to print out a syntax tree, where i only need to print the literals and not the tree structure itself. It will be another modification before it can do that i think, but now there is good inspiration :)
