### ISSUE TITLE
IsString (m Doc)

### ISSUE THREAD

**Issue by phadej** [ivan-m/wl-pprint-text#16]
is quite bad idea. It overlaps too many things

```
Overlapping instances for IsString (HtmlT m a2)
        arising from the literal ‘"JSON"’
      Matching instances:
        instance (Monad m, a ~ ()) => IsString (HtmlT m a)
          -- Defined in ‘Lucid.Base’
        ...plus one instance involving out-of-scope types
          instance [safe] Applicative m =>
                          IsString
                            (m wl-pprint-text-1.1.1.0:Text.PrettyPrint.Leijen.Text.Doc)
            -- Defined in ‘wl-pprint-text-1.1.1.0:Text.PrettyPrint.Leijen.Text.Monadic’
```

**Comment by ivan-m** [comment]
I see your point.  I'm a tad reluctant to remove this though because it would require a major version bump (and it's highly likely that I'm using it in `graphviz`).

Would setting `{-# OVERLAPPABLE #-}` be sufficient do you think?

**Comment by phadej** [comment]
AFAICS `HtmlT m a` is not comparable with `m Doc`, neither is more generic than other. `a ~ Doc => m a` would be, but that instance would be very bad (as it's head is super generic).

**Comment by ekmett** [comment]
Thanks!
