### ISSUE TITLE
Build failure with ghc 8.4

### ISSUE THREAD

**Issue by DanBurton** [ivan-m/wl-pprint-text#18]
```
Building library for wl-pprint-text-1.1.1.0..

[2 of 2] Compiling Text.PrettyPrint.Leijen.Text.Monadic ( Text/PrettyPrint/Leijen/Text/Monadic.hs, dist/build/Text/PrettyPrint/Leijen/Text/Monadic.o )

Text/PrettyPrint/Leijen/Text/Monadic.hs:24:35: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘PP.<>’,
                             imported from ‘Prelude.Compat’ at Text/PrettyPrint/Leijen/Text/Monadic.hs:73:1-36
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.Leijen.Text.Monadic.<>’,
                             defined at Text/PrettyPrint/Leijen/Text/Monadic.hs:258:1
   |
24 |    empty, char, text, textStrict, (<>), nest, line, linebreak, group, softline,
   |                                   ^^^^

```

**Comment by ivan-m** [comment]
I think this is because `base-compat` doesn't support base-4.10 yet, so there's some discrepancy.

However, the current build failure is solely for GHC 7.4.2.  So I suppose the option is to drop support for it.

**Comment by clinty** [comment]
Did you mean base-4.11?

**Comment by nomeata** [comment]
Is my understanding correct that this is blocked on `base-compat`? I reported the lack of 8.4 support there: https://github.com/haskell-compat/base-compat/issues/44

**Comment by RyanGlScott** [comment]
We are currently preparing a 8.4-ready release of `base-compat` in https://github.com/haskell-compat/base-compat/pull/43. We have not done so yet since there are a couple of design questions we are working through in https://github.com/haskell-compat/base-compat/issues/36. (You may wish to chime in if you have an opinion on them.)

**Comment by nomeata** [comment]
@ivan-m, a 8.4-compatible version of `base-compat` has been released.

**Comment by ilovezfs** [comment]
🎉

**Comment by ocramz** [comment]
@ivan-m ping !
