### ISSUE TITLE
Render tables

### ISSUE THREAD

**Issue by k0ral** [ivan-m/wl-pprint-text#3]
Is it possible to concatenate multiple columns using a top alignment (like what [boxes][1] does) ?
This is essential in correctly rendering tables, but maybe `wl-pprint-text` wasn't meant to do that ?
I've tried the following (obviously wrong):

```
> vcat ["a1", "a2", "a3"] <+> vcat ["b1", "b2", "b3"]
a1
a2
a3 b1
b2
b3
```

[1]: http://hackage.haskell.org/package/boxes

**Comment by ivan-m** [comment]
wl-pprint-text is basically the wl-pprint library using Text rather than String, so I don't think it's going to work this way and alas `boxes` is the way to go.
